version: "3.5"

services:
  fe:
    container_name: "${APP_NAME}-fe"
    build:
      context: .
      args:
        GIT_URL: ${GIT_URL}
      dockerfile: Dockerfile
    volumes:
      - "${SOURCE_PATH}:/app"
      - "/app/node_modules"
    ports:
      - "4201:4200"
  # namhoa-fe-prod:
  #   container_name: namhoa-fe-prod
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-prod
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`anatoki.com`)"
  #     - "traefik.http.routers.whoami.entrypoints=web"
